# AnastrisTNG 简单介绍

In [2]:
from AnastrisTNG import TNGsimulation, TNGtools, Anatools  #导入模块
import numpy as np
import matplotlib.pyplot as plt

In [3]:
run = 'TNG50-1'
BasePath = '/home/yxi/Simulation/sims/' + run + '/output/'         #模拟数据所在位置
snap=99                                                             #需要分析的快照序号

In [ ]:
Snapshot=TNGsimulation.Snapshot(BasePath,snap)                     #初始化Snapshot
Snapshot    # len = 0, 即 没有粒子载入

<Snapshot "TNG50-1_snapshot99" len=0>

In [7]:
Snapshot.properties               #Simdict，字典，保存所有关于该snapshort的信息

{'filedir': '/home/yxi/Simulation/sims/TNG50-1/output/',
 'run': 'TNG50-1',
 'a': np.float64(0.9999999999999998),
 'h': np.float64(0.6774),
 'omegaM0': np.float64(0.3089),
 'omegaL0': np.float64(0.6911),
 'omegaB0': 0.0486,
 'sigma8': 0.8159,
 'ns': 0.9667,
 'boxsize': Unit("3.50e+04 a kpc h**-1"),
 'Halos_total': np.int32(10247012),
 'Subhalos_total': np.int32(5688113),
 'Snapshot': 99,
 'eps': SimArray(0.195, 'kpc h**-1'),
 'Mdm': SimArray(3.1e-05, '1.00e+10 Msol h**-1'),
 'baseunits': [Unit("kpc"), Unit("km s**-1"), Unit("Msol")],
 'staunit': ['nH',
  'Halpha',
  'em',
  'ne',
  'temp',
  'mu',
  'c_n_sq',
  'p',
  'cs',
  'c_s',
  'acc',
  'phi',
  'age',
  'tform',
  'SubhaloPos',
  'sfr']}

a为尺度因子；h，omegaM0，omegaL0，omegaB0，sigma8，ns 为模拟所用的宇宙学参数；boxsize为模拟盒子的大小；Halos_total 为该snapshot中halo的总数；Subhalos_total 为subhalo的总数；filedir 为文件所在位置；run 为具体什么模拟； Snapshot 为snapshot序号；eps 为引力软化尺度；Mdm 为单个暗物质粒子质量；baseunits 当转化为基本物理单位后 采用的单位制。

In [8]:
Snapshot.cosmology           #获取宇宙学参数

{'h': np.float64(0.6774),
 'omegaM0': np.float64(0.3089),
 'omegaL0': np.float64(0.6911),
 'omegaB0': 0.0486,
 'sigma8': 0.8159,
 'ns': 0.9667}

In [9]:
Snapshot.boxsize              #获取boxsize    

Unit("3.50e+04 a kpc h**-1")

In [10]:
print('尺度因子:',Snapshot.a)
print('宇宙时间:',Snapshot.t)
print('回顾时间:',Snapshot.tLB)
print('红移:',Snapshot.z)             

尺度因子: 0.9999999999999998
宇宙时间: 1.38e+01 Gyr
回顾时间: 6.13e-15 Gyr
红移: 2.220446049250313e-16


In [11]:
Snapshot.rho_crit       #当前时刻的宇宙学临界密度

Unit("5.48e+02 km**2 G**-1 Mpc**-2 s**-2")

In [12]:
print('可以载入的属性：',Snapshot.loadable_parameters.keys())  #查看可以载入的属性，groupcatalogs和snapshots
print('groupcatalogs: ',Snapshot.loadable_parameters['groupcatalogs'].keys())
print('snapshots: ',Snapshot.loadable_parameters['snapshots'].keys())

可以载入的属性： dict_keys(['groupcatalogs', 'snapshots'])
groupcatalogs:  dict_keys(['halo', 'subhalo'])
snapshots:  dict_keys(['gas', 'star', 'dm', 'bh'])


### 载入粒子

In [11]:
Snapshot.load_particle_para       #字典，查看导入粒子的 设置，

{'particle_field': 'dm,star,gas,bh',
 'Basefields': ['Coordinates', 'Velocities', 'Masses', 'ParticleIDs'],
 'star_fields': [],
 'gas_fields': [],
 'dm_fields': [],
 'bh_fields': []}

particle_field 为载入粒子类型，一共这四种类型：暗物质粒子，恒星粒子，气体粒子，黑洞粒子。默认四个都载入。\
Basefields 为基本属性，即所有类型粒子都需导入的属性。\
star_fields，gas_fields... 为特定类型粒子的特殊属性。\
关于 粒子属性 更详细介绍 查看； https://www.tng-project.org/data/docs/specifications/#sec1b

In [12]:
print('可以载入的气体粒子属性：',str(Snapshot.loadable_parameters['snapshots']['gas'].keys()))

可以载入的气体粒子属性： dict_keys(['CenterOfMass', 'Coordinates', 'Density', 'ElectronAbundance', 'EnergyDissipation', 'GFM_AGNRadiation', 'GFM_CoolingRate', 'GFM_Metallicity', 'GFM_Metals', 'GFM_MetalsTagged', 'GFM_WindDMVelDisp', 'GFM_WindHostHaloMass', 'InternalEnergy', 'InternalEnergyOld', 'Machnumber', 'MagneticField', 'MagneticFieldDivergence', 'Masses', 'NeutralHydrogenAbundance', 'ParticleIDs', 'Potential', 'StarFormationRate', 'SubfindDMDensity', 'SubfindDensity', 'SubfindHsml', 'SubfindVelDisp', 'Velocities'])


In [13]:
print('可以载入的恒星粒子属性：',(str(Snapshot.loadable_parameters['snapshots']['star'].keys())))

可以载入的恒星粒子属性： dict_keys(['BirthPos', 'BirthVel', 'Coordinates', 'GFM_InitialMass', 'GFM_Metallicity', 'GFM_Metals', 'GFM_MetalsTagged', 'GFM_StellarFormationTime', 'GFM_StellarPhotometrics', 'Masses', 'ParticleIDs', 'Potential', 'StellarHsml', 'SubfindDMDensity', 'SubfindDensity', 'SubfindHsml', 'SubfindVelDisp', 'Velocities'])


In [14]:
#查看气体粒子的ElectronAbundance的描述
print((Snapshot.loadable_parameters['snapshots']['gas']['ElectronAbundance']))

Fractional electron number density with respect to the total hydrogen number density, so ne=ElectronAbundance*nH where nH=XH*rho/mp. Use with caution for star-forming gas (see comment below for NeutralHydrogenAbundance).


In [15]:
#查看，恒星粒子的GFM_StellarFormationTime的描述
print((Snapshot.parameter_describe('snapshots','star','GFM_StellarFormationTime')))

The exact time (given as the scalefactor) when this star was formed. Note: The only differentiation between a real star (>0) and a wind phase gas cell (<=0) is the sign of this quantity.


In [16]:
#设置 额外导入恒星粒子 的一些属性
Snapshot.load_particle_para['star_fields']=[
    'GFM_StellarFormationTime','GFM_StellarPhotometrics','BirthPos']
#设置 额外载入气体粒子 的一些属性
Snapshot.load_particle_para['gas_fields']=['GFM_Metals','ElectronAbundance','InternalEnergy','Density'] 

In [17]:
Snapshot.load_particle_para          

{'particle_field': 'dm,star,gas,bh',
 'Basefields': ['Coordinates', 'Velocities', 'Masses', 'ParticleIDs'],
 'star_fields': ['GFM_StellarFormationTime',
  'GFM_StellarPhotometrics',
  'BirthPos'],
 'gas_fields': ['GFM_Metals',
  'ElectronAbundance',
  'InternalEnergy',
  'Density'],
 'dm_fields': [],
 'bh_fields': []}

In [18]:
Snapshot.load_halo(400)   #导入该snapshot下id为400的halo
# 使用Snapshot.load_subhalo() 导入subhalo，
# 在未改变坐标前，可以多次载入粒子，
# 改变坐标或计算引力后，载入粒子功能被锁定，不能再载入粒子

In [19]:
Snapshot.s    #整个snap已载入的恒星粒子

<SimSnap "TNG50-1_snapshot99::star" len=473612>

In [20]:
Snapshot.s.keys()

['GFM_StellarPhotometrics',
 'vy',
 'SubhaloID',
 'y',
 'z',
 'pos',
 'x',
 'HaloID',
 'iord',
 'aform',
 'mass',
 'BirthPos',
 'vz',
 'vx',
 'BirthPos_y',
 'vel',
 'BirthPos_x',
 'BirthPos_z']

In [21]:
Snapshot.load_subhalo(549516)

In [22]:
Snapshot.subhalos[549516].s    #该subhalo 的恒星

<SimSnap "TNG50-1_snapshot99:Subhalo_549516::star" len=691113>

In [23]:
Snapshot.subhalos[549516].s['mass']

SimArray([4.19749813e-06, 3.74249703e-06, 4.18186346e-06, ...,
          4.47807588e-06, 2.42827514e-06, 7.66162611e-06], '1.00e+10 Msol h**-1')

In [24]:
Snapshot.subhalos[549516].physical_units()   #物理单位

In [25]:
Snapshot.subhalos[549516].g['mass']

#注意 所有载入该snapshot的粒子，都在统一的坐标系统下处理

SimArray([159340.71936777, 116680.83950072, 107909.88822252, ...,
          106162.13182961,  70180.66054814,  61296.05599787], 'Msol')

In [ ]:
sub10=Snapshot.load_particle(10)  # 默认载入subhalo，如果为halo 需要传入关键字 groupType= 'Halo'
# 载出 ID为10的subhalo，不会载入到snapshot中，
# 对于TNG-Cluster 支持 groupType= 'Zoom'，

In [27]:
sub10

<Subhalo "TNG50-1_snapshot99_Subhalo_10" SubhaloID=10>

In [32]:
sub10.bh.keys()

['vy',
 'SubhaloID',
 'y',
 'z',
 'pos',
 'x',
 'HaloID',
 'iord',
 'mass',
 'vz',
 'vx',
 'vel']

In [ ]:
## 使用多进程匹配tracerIDs， 4进程 时间花费十几分钟，内存需要<~7G
#Traceparticle=TNGtools.findtracer(
    # Snapshot.properties['filedir'],99,Snapshot.subhalos['549516'].PT.s['iord'],NP=4)

In [23]:
#查询星系的并合历史
merger_require_fields=['SubhaloPos','SubhaloMassType']
min_massratio=0.1
merger_h=TNGsimulation.merger_history(
    Snapshot.properties['filedir'],99,549516,fields=merger_require_fields,minMassRatio=min_massratio)

In [25]:
print(list(merger_h.keys()))

['MergerEvents', 'MassRatio', 'First-SubhaloPos', 'Next-SubhaloPos', 'First-SubhaloMassType', 'Next-SubhaloMassType', 'numMergers']


In [26]:
# 与MassRatio 和SnapNum 的index相对应
merger_h['First-SubhaloPos']

[SimArray([16906.38 ,  8993.423, 13470.431], dtype=float32, 'kpc'),
 SimArray([3902.126, 2017.054, 3151.785], dtype=float32, 'kpc'),
 SimArray([3051.3003, 1567.3752, 2467.7275], dtype=float32, 'kpc'),
 SimArray([3051.3003, 1567.3752, 2467.7275], dtype=float32, 'kpc')]

In [31]:
#查询星系的演化历史
evo_require_fields=['SubhaloPos','SubhaloMassType','SubhaloSFR']
evo_h=TNGsimulation.galaxy_evolution(
    Snapshot.properties['filedir'],99,549516,fields=evo_require_fields)

In [32]:
#与SnapNum 相对应
evo_h['SubhaloSFR']

SimArray([3.9889784e+00, 3.4957864e+00, 3.5073688e+00, 3.5457451e+00,
          4.3617549e+00, 4.6761918e+00, 5.3235936e+00, 5.0113964e+00,
          5.2727051e+00, 5.6502700e+00, 5.1161175e+00, 5.2896161e+00,
          5.0907879e+00, 3.8918951e+00, 3.7160950e+00, 4.4908547e+00,
          5.1198993e+00, 6.2067761e+00, 6.2812562e+00, 5.9627752e+00,
          6.8523912e+00, 5.8605933e+00, 4.9921360e+00, 4.7386498e+00,
          5.4448686e+00, 5.2927856e+00, 5.2197185e+00, 4.5819983e+00,
          4.7386193e+00, 4.1795831e+00, 4.0303149e+00, 3.9073701e+00,
          5.2362466e+00, 4.3555717e+00, 3.8110013e+00, 3.9635782e+00,
          3.8844423e+00, 4.3330188e+00, 6.6063643e+00, 9.0028410e+00,
          7.1706181e+00, 5.7971177e+00, 4.2302632e+00, 3.8681424e+00,
          3.7638419e+00, 5.4098053e+00, 7.9069738e+00, 8.7179346e+00,
          7.9329586e+00, 6.3881173e+00, 6.2105169e+00, 5.1204367e+00,
          5.4738622e+00, 7.1349149e+00, 5.2036991e+00, 4.9480271e+00,
          3.1808419e

In [27]:
Snapshot['SubhaloID']        #粒子所属的SubhaloID，如果为-1 则为没有激活subhalo

SimArray([    -1,     -1,     -1, ..., 549516,     -1, 549516],
         dtype=int32)

In [28]:
Snapshot['HaloID']        #HaloID 已有

SimArray([400, 400, 400, ..., 249, 400, 249], dtype=int32)

In [33]:
Snapshot.load_GC()    #导入group cata

In [34]:
Snapshot.GC_loaded_Halo  # 该halo 已导入group catalo

array([400])

In [37]:
Snapshot.halos[400].center(mode='ssc')   # 中心坐标  默认 方法使用 shrink sphere center  

SimArray([ 6260.91732938, 24152.90859663, 18309.46831678], 'a kpc h**-1')

In [38]:
Snapshot.halos[400].center(mode='com')  #质心

SimArray([ 6260.50863816, 24153.73984727, 18311.79302046], 'a kpc h**-1')

In [39]:
Snapshot.halos[400].GC['GroupCM']   # group catalog 给的质心坐标

SimArray([ 6260.51 , 24153.738, 18311.791], dtype=float32, 'a kpc h**-1')

In [40]:
Snapshot.halos[400].GC['GroupPos']   # group catalog 给的 引力势最低点

SimArray([ 6260.937, 24152.902, 18309.434], dtype=float32, 'a kpc h**-1')

In [45]:
cen_halo400=Snapshot.halos[400].center(mode='ssc')
#计算两百倍临界密度半径
Snapshot.halos[400].R_vir(cen=cen_halo400,overden=200) 

SimArray(116.18854062, 'a kpc h**-1')

In [46]:
#计算与官网一致
Snapshot.halos[400].GC['Group_R_Crit200']  

SimArray(116.34011, dtype=float32, 'a kpc h**-1')

In [47]:
#计算五百倍临界密度半径
Snapshot.halos[400].R_vir(cen=cen_halo400,overden=500) 

SimArray(81.4551209, 'a kpc h**-1')

In [48]:
#计算与官网一致
Snapshot.halos[400].GC['Group_R_Crit500']

SimArray(81.223, dtype=float32, 'a kpc h**-1')

In [49]:
Snapshot.PT_loaded_Subhalo   #已导入粒子的subhalo  ，可以直接唤醒，并给粒子分配subhaloID
# Snapshot.subhalos[Snapshot.PT_loaded_Subhalo]   此方法为所有已经载入粒子的Subhalo匹配粒子  10^6 ~ 20s 
# 该halo中的第一个编号subhalo 即为中心星系

array([549516, 590792, 590793, 590794, 590795, 590796, 590797, 590798,
       590799, 590800, 590801, 590802, 590803, 590804, 590805, 590806,
       590807, 590808, 590809, 590810, 590811, 590812, 590813, 590814,
       590815, 590816, 590817, 590818, 590819, 590820, 590821, 590822,
       590823, 590824, 590825, 590826, 590827, 590828, 590829, 590830,
       590831, 590832, 590833, 590834, 590835, 590836, 590837, 590838,
       590839, 590840, 590841, 590842, 590843, 590844, 590845, 590846,
       590847, 590848, 590849, 590850, 590851, 590852, 590853, 590854,
       590855, 590856, 590857, 590858, 590859, 590860, 590861, 590862,
       590863, 590864, 590865, 590866, 590867, 590868, 590869, 590870,
       590871, 590872, 590873, 590874, 590875, 590876, 590877, 590878,
       590879, 590880, 590881, 590882, 590883, 590884, 590885, 590886,
       590887, 590888, 590889, 590890, 590891, 590892, 590893, 590894,
       590895, 590896, 590897, 590898, 590899, 590900, 590901, 590902,
      

In [50]:
Snapshot.subhalos[590792]   #激活

<Subhalo "TNG50-1_snapshot99" SubhaloID=590792>

In [54]:
print(Snapshot['SubhaloID'])      
#已匹配SubhaloID，此时若为-1 则表明不在任何Subhalo中或未激活
# Snapshot.subhalos[Snapshot.PT_loaded_Subhalo]   使用此语句则全部激活

[590792 590792 590792 ...     -1     -1 590792]


In [55]:
Snapshot.status_loadPT       
#这里查看能否继续load粒子，若已经改变了已载入粒子的坐标等，则不能再load粒子

'locked'